### 서버 연결 확인
GET http://localhost:3000/


### 제품 목록 조회
GET http://localhost:3000/products?pageSize=4&orderBy=recent

### 제품 목록 조회 (키워드 포함)
GET http://localhost:3000/products?page=1&pageSize=4&orderBy=recent&keyWord=최대

### 제품 상세 조회
GET http://localhost:3000/products/67d6fbd987b2e4b147b8a93

### 제품 생성
POST http://localhost:3000/products/registration
Content-Type: application/json

{
  "name": "새로 등록한 아이템",
  "description": "청축 스위치가 장착된 게이밍용 기계식 키보드입니다. RGB 백라이트 기능을 지원합니다."
}

### 제품 수정
PATCH http://localhost:3000/products/update/67d6fbd987b2e4b147b8a937
Content-Type: application/json

{
  "name": "진짜 수정한 아이템"
}


### 제품 삭제
DELETE http://localhost:3000/products/delete/67d6fbd987b2e4b147b8a937

