### 아티클 조회 (진행도: OK)

GET http://localhost:3000/articles/1

### 아티클 목록조회 (진행도: OK)

GET http://localhost:3000/articles

### 프로덕트 목록조회 (진행도: OK)

GET http://localhost:3000/products

### 프로덕트 조회 (진행도: OK)

GET http://localhost:3000/products/1

### 로그인 (진행도: OK)

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email":"friday123@email.com",
  "password":"friday123"
}

### 회원가입 (진행도: OK)

POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "nickname": "friday",
  "email": "friday123@email.com",
  "password": "friday123"
}

### 게시물 등록 (로그인 필요, 진행도: 로그인 토큰으로 게시물등록 OK)

POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Njc3ODk3NSwiZXhwIjoxNzQ2NzgyNTc1fQ.6OBUQY4Oyw0D93w8Y2dle2xlMYN2w2FP1SfUkjatdJo

{
  "title": "LG모니터 중고",
  "content": "LCD 모니터에요. 확인 후 연락주세요!",
  "writer": "sevendays"
}

### multer 업로드 (진행도: text/plain OK -> 실제 이미지 전송시 image/png 로 개선 필요)

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=---------------------------abcd123456

-----------------------------abcd123456
Content-Disposition: form-data; name="image"; filename="blank.txt"
Content-Type: text/plain

This is the content of the file.
-----------------------------abcd123456--

###