### 아티클 조회

GET http://localhost:3000/articles/1

### 아티클 목록조회

GET http://localhost:3000/articles

### 프로덕트 목록조회

GET http://localhost:3000/products

### 프로덕트 조회

GET http://localhost:3000/products/2

### 로그인

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email":"friday123@email.com",
  "password":"friday123"
}

### 회원가입

POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "nickname": "friday",
  "email": "friday123@email.com",
  "password": "friday123"
}

### 아티클 등록

POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzAwOTE5OSwiZXhwIjoxNzQ3MDEyNzk5fQ.sdATdMiveU1w9HfAtyeZyKBKir9Cp1qqqPsEN1ub2xM

{
  "title": "중고마켓 판다마켓 맞나요?",
  "content": "중고물품 팔려고 하는데요?",
  "writer": "sevendays"
}

### 프로덕트 등록

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzAxMjA3MywiZXhwIjoxNzQ3MDE1NjczfQ.Or6Q-7g-Jy3XCflsnHznJlxMTA7w2YN-3XPDiMHGjOw

{
  "name": "Samsung MP3 플레이어",
  "price": 45000
}

### 사진 업로드 (실제 이미지 전송시 image/png 로 개선 필요)

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=---------------------------abcd123456

-----------------------------abcd123456
Content-Disposition: form-data; name="image"; filename="blank.txt"
Content-Type: text/plain

This is the content of the file.
-----------------------------abcd123456--

### 