openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /auth/signUp:
    post:
      summary: 회원가입
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@email.com
                nickname:
                  type: string
                  example: nickname
                password:
                  type: string
                  example: password
                passwordConfirmation:
                  type: string
                  example: password
              required:
                - email
                - nickname
                - password
                - passwordConfirmation
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                Success:
                  $ref: '#/components/examples/AuthResponseExample'

  /auth/signIn:
    post:
      summary: 로그인
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@email.com
                nickname:
                  type: string
                  example: nickname
                password:
                  type: string
                  example: password
                passwordConfirmation:
                  type: string
                  example: password
              required:
                - email
                - nickname
                - password
                - passwordConfirmation
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                Success:
                  $ref: '#/components/examples/AuthResponseExample'

  /auth/refresh-Token:
    post:
      summary: 토큰 갱신
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: string
              required:
                - refreshToken
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: string

components:
  schemas:
    AuthResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: integer
              example: 123
            nickname:
              type: string
              example: nickname
            image:
              type: string
              nullable: true
              example: null
            createdAt:
              type: string
              format: date-time
              example: "2025-05-08T08:13:52.165Z"
            updatedAt:
              type: string
              format: date-time
              example: "2025-05-08T08:13:52.165Z"
            email:
              type: string
              example: example1@email.com
        accessToken:
          type: string
          example: accessToken
        refreshToken:
          type: string
          example: refreshToken

  examples:
    AuthResponseExample:
      value:
        user:
          id: 123
          nickname: nickname
          image: null
          createdAt: "2025-05-08T08:13:52.165Z"
          updatedAt: "2025-05-08T08:13:52.165Z"
          email: example1@email.com
        accessToken: accessToken
        refreshToken: refreshToken
