@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5NzkyMDU0LCJleHAiOjE3NDk3OTI5NTR9.qv9dSiwEHAWnU_JmAKIUxqB8ix8juJgZBy-fRf4iE1E
# 게시글 API

### 게시글 목록 조회
GET http://localhost:7777/articles/?offset=0&limit=10
# Authorization: {{accessToken}}

### 게시글 조회 (인기순)
GET http://localhost:7777/articles?offset=0&limit=10&sort=popular
# Authorization: {{accessToken}}

### 게시글 상세 조회
GET http://localhost:7777/articles/cmbu4ek140001uproep34gk7v
# Authorization: {{accessToken}}

### 게시글 등록
POST http://localhost:7777/articles
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "테스트할 게시글",
  "content": "새로 등록한 게시글의 내용입니다.5"
}

### 게시글 수정
PATCH http://localhost:7777/articles/cmbu4ek140001uproep34gk7v
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "저녁에 러닝 뛰어야겠다 하하하",
  "content": "수정된 게시글의 내용입니다."
}

### 게시글 삭제
DELETE http://localhost:7777/articles/cmbu4ek140001uproep34gk7v
Authorization: {{accessToken}}

### 게시글 좋아요 추가
POST http://localhost:7777/articles/cmbu4ek140001uproep34gk7v/like
Authorization: {{accessToken}}

### 게시글 좋아요 삭제
DELETE http://localhost:7777/articles/cmbu4ek140001uproep34gk7v/like
Authorization: {{accessToken}}

