# 인증 API

### 로그인
POST http://localhost:7777/auth/signIn
Content-Type: application/json

{
  "email": "gksktl111@naver.com",
  "password": "1rhdiddl!"
}

### 로그아웃
POST http://localhost:7777/auth/logOut
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5Nzc1MDMzLCJleHAiOjE3NDk3NzU5MzN9.Ffr-jL6bZmTxT7pGN_Zs3RIgleTcJHObN3sE8iAgXCg

### 회원가입
POST http://localhost:7777/auth/signUp
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "123",
  "nickname": "홍길동"
}


### 토큰 갱신
// 왜 유저 아이디가 다르게 전달되지?
// 이전 쿠키값이 아직 남아 있었음 이유는 로그인시에만 쿠키가 저장되기 때문!
// 정확히는 쿠키의 maxAge와 토큰의 expiresIn의 간극에 따른 오류였음
POST http://localhost:7777/auth/token/refresh
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5Nzc1MDg1LCJleHAiOjE3NTA2MzkwODV9.nFyI-2ijwllD1GOJTj5tz3uiIifzbaMWOFoG9RmCckw