@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5NzgxOTIwLCJleHAiOjE3NDk3ODI4MjB9.O8G_C1QL9cdnZwkuGj4xVRgpCiNt7TfZnFPg_Wfjqj0
@articleId = cmbu562ud0005up7c5j4x6i1j

@productId = cmbu51cy40001up7cadhlsn2r

# 댓글 API

### 게시글 댓글 목록 조회
GET http://localhost:7777/articles/{{articleId}}/comments


### 게시글 댓글 등록
POST http://localhost:7777/articles/{{articleId}}/comments
Content-Type: application/json
Authorization: {{accessToken}}

{
  "content": "게시글에 새로 등록한 댓글입니다. 3"
}

### 상품 댓글 목록 조회
GET http://localhost:7777/products/{{productId}}/comments


### 상품 댓글 등록
POST http://localhost:7777/products/{{productId}}/comments
Content-Type: application/json
Authorization: {{accessToken}}

{
  "content": "상품에 새로 등록한 댓글입니다."
}

### 댓글 수정
PATCH http://localhost:7777/comments/cmbu7098x0005ups8z156dt7s
Content-Type: application/json
Authorization: {{accessToken}}

{
  "content": "수정된 댓글입니다."
}

### 댓글 삭제
DELETE http://localhost:7777/comments/cmbu7098x0005ups8z156dt7s
Authorization: {{accessToken}}