@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5Nzc4NTg1LCJleHAiOjE3NDk3Nzk0ODV9.dbC5nEu3XZ0d2IVvV74NVe6eEtUVX8vC0MwN3xFmky8

# 제품 API

### 제품 목록 조회
GET http://localhost:7777/products?page=0&pageSize=10&orderBy=likes
Authorization: {{accessToken}}

### 제품 목록 조회 (키워드 포함)
GET http://localhost:7777/products?page=0&pageSize=4&orderBy=recent&keyWord=새로
Authorization: {{accessToken}}

### 제품 상세 조회
GET http://localhost:7777/products/cmbu2yws60001up2417zl6bi9
Authorization: {{accessToken}}

### 제품 생성
POST http://localhost:7777/products
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "새로 등록한 아이템",
  "description": "청축 스위치가 장착된 게이밍용 기계식 키보드입니다.",
  "price": 150000,
  "tags": ["키보드", "게이밍"]
}

### 제품 수정
PATCH http://localhost:7777/products/cmbu2yws60001up2417zl6bi9
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "수정된 아이템 입니돠ㅏㅏㅏ",
  "description": "수정된 아이템 입니돠ㅏㅏㅏ",
  "price": 160000
}

### 제품 삭제
DELETE http://localhost:7777/products/cmbu2yws60001up2417zl6bi9
Authorization: {{accessToken}}

### 제품 좋아요 추가
POST http://localhost:7777/products/cmbu2yws60001up2417zl6bi9/like
Authorization: {{accessToken}}

### 제품 좋아요 삭제
DELETE http://localhost:7777/products/cmbu2yws60001up2417zl6bi9/like
Authorization: {{accessToken}}