### 유저 정보 확인
GET http://localhost:7777/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWFrZWFqcm0wMDAwdXBlY21jazN1NzNzIiwiaWF0IjoxNzQ3MDM3MjI1LCJleHAiOjE3NDcwMzgxMjV9.WGmHh8xqLROfc1dgmBapCOYMEsnHPqnPbHtBm8aDNmQ


### 유저 정보 수정
PATCH http://localhost:7777/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWFrZWFqcm0wMDAwdXBlY21jazN1NzNzIiwiaWF0IjoxNzQ3MDM3MjI1LCJleHAiOjE3NDcwMzgxMjV9.WGmHh8xqLROfc1dgmBapCOYMEsnHPqnPbHtBm8aDNmQ

{
  "nickname": "홍길동"
}

### 유저 비밀번호 수정
PATCH http://localhost:7777/user/me/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWFrZWFqcm0wMDAwdXBlY21jazN1NzNzIiwiaWF0IjoxNzQ3MDM3MjI1LCJleHAiOjE3NDcwMzgxMjV9.WGmHh8xqLROfc1dgmBapCOYMEsnHPqnPbHtBm8aDNmQ

{
  "currentPassword": "123",
  "newPassword": "1234"
}
