@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJya25tZGwwMDAwaHAzMmhvcjYxaTR2IiwiaWF0IjoxNzQ5NzgyMDQ2LCJleHAiOjE3NDk3ODI5NDZ9.-1xTGMYtiMvyyqfP1iBzD5eDWJvmKYnTs6JoK4_JWM4

### 유저 정보 확인
GET http://localhost:7777/user/me
Content-Type: application/json
Authorization: {{accessToken}}

### 유저 정보 수정
PATCH http://localhost:7777/user/me
Content-Type: application/json
Authorization: {{accessToken}}

{
  "nickname": "홍길동"
}

### 유저 비밀번호 수정
PATCH http://localhost:7777/user/me/password
Content-Type: application/json
Authorization: {{accessToken}}

{
  "currentPassword": "1rhdiddl!",
  "newPassword": "1rhdiddl!"
}
