@baseUrl = http://3.37.87.65:5050
# 또는 배포 환경에 따라:
# @baseUrl = https://api.yourdomain.com
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1MDkxODI0OSwiZXhwIjoxNzUwOTIxODQ5fQ.brJwyUx4cddSnO0Z1i6ISN6M_IWPUgMBfihNv5wvDWw

### 로그인
POST {{baseUrl}}/auth/signIn
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"test"
}


### 회원가입
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "nickname": "friday",
  "email": "friday123@email.com",
  "password": "friday123"
}



### 사진 업로드 (실제 이미지 전송시 image/png 로 개선 필요)
# 업로드 서버도 동일한 포트(5050)를 사용한다고 가정하고 {{baseUrl}}을 적용했습니다.
# 만약 업로드 서버가 여전히 3000 포트를 사용한다면, 해당 URL을 직접 명시해야 합니다.
# 예: POST http://localhost:3000/upload
# POST {{baseUrl}}/upload
# Content-Type: multipart/form-data; boundary=---------------------------abcd123456

# -----------------------------abcd123456
# Content-Disposition: form-data; name="image"; filename="your_image.png"
# Content-Type: image/png

# This is the content of the file.
# -----------------------------abcd123456--


### 프로덕트 목록조회
GET {{baseUrl}}/products

### 프로덕트 조회
GET {{baseUrl}}/products/8


### 프로덕트 등록
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Samsung 갤럭시 노트 20",
  "price": 600000
}


### 프로덕트 삭제
DELETE {{baseUrl}}/products/7
Content-Type: application/json
Authorization: Bearer {{authToken}}


### 프로덕트 수정
PUT {{baseUrl}}/products/8
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Samsung 갤럭시 탭 S7 FE",
  "price": 230000
}


### 아티클 조회
GET {{baseUrl}}/articles/1


### 아티클 목록조회
GET {{baseUrl}}/articles


### 아티클 등록
POST {{baseUrl}}/articles
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "중고마켓 판다마켓 맞나요?",
  "content": "중고물품 팔려고 하는데요?",
  "writer": "sevendays"
}