###게시글 등록
POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "날씨가ㅗㄱ쇼도ㅓㅜㅜ아요",
    "content": "오늘 날씨가 참 좋아요"
}

###게시글 목록 조회
GET http://localhost:3000/articles

###베스트 게시글 목록 조회
GET http://localhost:3000/articles?take=3


###게시글 상세 조회
GET http://localhost:3000/articles/5


###게시글 수정
PATCH  http://localhost:3000/articles/24
Content-Type: application/json

{
    "title": "날씨가 좋아요",
    "content": "어제는 추었어요"
}

###게시글 삭제
DELETE http://localhost:3000/articles/25