@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMGEyMTM1Ni04NjkyLTQ4ZGQtYWM3My1mYWNkNWVkZTc0YTciLCJpYXQiOjE3NTAzODYzNDcsImV4cCI6MTc1MDM4OTk0N30.BaX5CBdJ-Z3FcB-3mO8yOQLms_L7UqRo5eueTm9x-NU

### 게시글 댓글 목록 조회
GET http://localhost:8080/articles/1/comments

### 게시글 댓글 등록
POST http://localhost:8080/articles/1/comments
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "content": "뎃글댓글"
}

### 상품 댓글 목록 조회
GET http://localhost:8080/products/1/comments

### 상품 댓글 등록
POST http://localhost:8080/products/1/comments
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "content": "댓글댓글"
}

### 댓글 수정
PATCH http://localhost:8080/comments/1
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "content": "수정된 댓글"
}

### 댓글 삭제
DELETE http://localhost:8080/comments/28
Cookie: accessToken={{accessToken}}

### 댓글 목록 무한스크롤
GET http://localhost:8080/products/1/comments?cursor=2&limit=3
Cookie: accessToken={{accessToken}}
