### 상품 등록 (여러 이미지 한번에 업로드 추후 수정)
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0OTY5NDc1MCwiZXhwIjoxNzQ5Njk4MzUwfQ.jpaGwiILt7NgO-LMfxIPoAmdekCXe70vlAR-8QVjLmM

{
    "name": "장원영 굿즈 모음",
    "description": "레어템 다수 보유",
    "price": 50000,
    "tags": ["한정판", "인기"],
    "images": ["/uploads/1749694617772.png"]
}

### 상품 목록 조회
GET http://localhost:3000/products?page=1&pageSize=10&orderBy=recent

### 상품 상세 조회
GET http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0OTcwNTUyOCwiZXhwIjoxNzQ5NzA5MTI4fQ.abynpN2pe7-5OW_TXnYtQxhgnhkY70fY6pcqZJRBb6g

### 수정, 삭제는 프론트에서 연결하고 확인함
